grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/task-mservice.log

system:
  allowed_origins: 
  - https://campaign-center-admin-web.vercel.app
  - https://finverse-web.vercel.app
  - http://localhost:3000

kafka:
  enabled: true
  brokers:
    - localhost:9092
  group_id: task-mservice
  client_id: task-mservice
  topics:
    - deposit.events
    - user.events.registered
